### ISSUE TITLE
Exception ignored in: <function Connection.__del__ at 0x105ec3830>

### ISSUE THREAD

**Issue by 631068264** [Pirionfr/sqlalchemy_phoenix#1]
```
Exception ignored in: <function Connection.__del__ at 0x105ec3830>
Traceback (most recent call last):
  File "/Users/wyx/loh_workspace/data-process/.env/lib/python3.7/site-packages/pyphoenix/connection.py", line 43, in __del__
  File "/Users/wyx/loh_workspace/data-process/.env/lib/python3.7/site-packages/pyphoenix/connection.py", line 71, in close
  File "/Users/wyx/loh_workspace/data-process/.env/lib/python3.7/site-packages/pyphoenix/avatica.py", line 187, in closeConnection
  File "/Users/wyx/loh_workspace/data-process/.env/lib/python3.7/site-packages/pyphoenix/avatica.py", line 102, in _apply
  File "/Users/wyx/loh_workspace/data-process/.env/lib/python3.7/site-packages/pyphoenix/avatica.py", line 41, in get_class
  File "/Users/wyx/loh_workspace/data-process/.env/lib/python3.7/importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 887, in _find_spec
ImportError: sys.meta_path is None, Python is likely shutting down
```

**Comment by Pirionfr** [comment]
which version of phoenix did you use ?

**Comment by 631068264** [comment]
phoenix  5.0.0.3.1.4.0    pyPhoenix-0.12.0

**Comment by Pirionfr** [comment]
you are not on the go repos go to https://github.com/Pirionfr/pyPhoenix
